"""
Add is_approved column to User

Revision ID: 244a10c91344
Revises: 99b3a2e76c48
Create Date: 2025-05-03 11:02:56.244957

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "244a10c91344"
down_revision = "99b3a2e76c48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_approved",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("0"),  # default to False for existing rows
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_approved")
    # ### end Alembic commands ###
